{{- if and .Values.config.userDb .Values.config.passwordDb }}
apiVersion: v1
kind: Secret
metadata:
  name: node-application-server-secret-db
data:
  userDb: {{ .Values.config.userDb | b64enc }}
  passwordDb: {{ .Values.config.passwordDb | b64enc }}
{{- end }}
---
{{- if and .Values.config.userDb .Values.config.passwordDb }}
apiVersion: v1
kind: Secret
metadata:
  name: node-application-server-secret-2
data:
  userDb: {{ .Values.config.userDb | b64enc }}
  passwordDb: {{ .Values.config.passwordDb | b64enc }}
{{- end }}
