kind: Service
apiVersion: v1
metadata:
  name: node-application-server
spec:
  selector:
    app.kubernetes.io/name: node-application-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 3000  